/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      yellow: "#fbe710",
      yellowHover: "#D4C304",
      blue: "#0076ff",
      blueHover: "#3391FF",
      orange: "#E84A37",
      orangeHover: "#D42C18",
      lightBlue: "#70A3FF",
      purple: "#230031",
      green: "#336042",
      light: "#f9fde6",
      gray: "#8492a6",
      white: "#ffffff",
      black: "#000000",
      red: "#E1341E",
      transparent: "transparent",
      lightHover: "#E0E0E0",
      analogueBlue: "#0900FF",
    },
    fontFamily: {
      sans: ["sans-serif", "sans-serif"],
      serif: ["Georgia", "serif"],
      mono: ["Menlo", "monospace"],
      comfortaa: ["var(--font-comfortaa)", "sans-serif"],
      poppins: ["var(--font-poppins)", "sans-serif"],
      lexend: ["var(--font-lexend)", "sans-serif"],
      arial: ["Arial", "sans-serif"],
      helvetica: ["Helvetica", "sans-serif"],
    },
    screens: {
      footerXM: "402px",
      lgMenu: "462px",
      xs: "480px",
      five: "500px",
      footerSM: "620px",
      sm: "640px",
      sev: "700px",
      md: "768px",
      eight: "800px",
      nav: "850px",
      ml: "896px",
      lg: "1024px",
      jobs: "1180px",
      tw: "1200px",
      xl: "1280px",
      mycommunity: "1520px",
      mycommunityGrid: "1550px",
      xxl: "1600px",
    },
  },
  plugins: [],
};
